---

- include: repository.yml

- name: Install latest passenger
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    name:
      - passenger
      - passenger-dev
  notify:
    - restart nginx

- name: Ensure nginx conf.d directory exists
  file:
    path: /etc/nginx/conf.d
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory

- name: Install passenger.conf for nginx
  template: src=passenger.conf.j2 dest=/etc/nginx/conf.d/passenger.conf owner=root group=root mode=0644

- name: Create the /var/run/passenger-instreg
  file: path="{{ passenger_tmp_dir }}" state=directory

- name: Install the sudoers file that will allow passenger_user to restart passenger
  template: src=sudoers_passenger.j2 dest=/etc/sudoers.d/{{ passenger_user }}_passenger owner=root group=root mode=0440
