---

- include: repository.yml

- name: Install latest passenger
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
   - passenger
   - passenger-dev
  notify:
    - restart nginx

- name: Ensure nginx conf.d directory exists
  file:
    path: /etc/nginx/conf.d
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory

- name: Install passenger.conf for nginx
  template: src=passenger.conf.j2 dest=/etc/nginx/conf.d/passenger.conf owner=root group=root mode=0644

- name: Install the sudoers file that will allow passenger_user to restart passenger
  template: src=sudoers_passenger.{{ ansible_distribution_release }}.j2 dest=/etc/sudoers.d/{{ passenger_user }}_passenger owner=root group=root mode=0440

# FIXME
- name: Create tmp dir for passenger
  file:
    path: /var/run/passenger-instreg
    owner: root
    group: root
    mode: 1777
    recurse: yes
    state: directory
