---

# Needed for add-apt-repository
- name: Install python3-software-properties
  ansible.builtin.apt:
    pkg:
      - python3-software-properties
    state: latest

- name: Add the Passenger repository key
  ansible.builtin.apt_key:
    url: "{{ passenger_repo_apt_key }}"
    state: present

- name: Apt via https
  ansible.builtin.apt:
    pkg: apt-transport-https
    state: latest

- name: Add Passenger repository
  ansible.builtin.apt_repository:
    repo: "{{ passenger_repo }}"
    state: present
